/*
------------------------------------------------
Generated by Cradle 2.0.2.0
https://github.com/daterre/Cradle

Original file: Bread.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Bread: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@Bread()
	{
		this.StartPassage = "The Bread Game";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
		passage19_Init();
		passage20_Init();
		passage21_Init();
		passage22_Init();
		passage23_Init();
		passage24_Init();
		passage25_Init();
		passage26_Init();
		passage27_Init();
		passage28_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Bread

	void passage1_Init()
	{
		this.Passages[@"Bread"] = new StoryPassage(@"Bread", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Welcolme to bread, the story begins as follows...");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("When you find yourself starving and craving a simple sandwich you decide to make " +
		    "one. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("What ingredients will you choose?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("First start by choosing which bread to make:", "First start by choosing which bread to make:", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2: First start by choosing which bread to make:

	void passage2_Init()
	{
		this.Passages[@"First start by choosing which bread to make:"] = new StoryPassage(@"First start by choosing which bread to make:", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("There are multiple options to choose from. You reach out and grab the recepie for" +
		    " your favorite type...");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("White" + " " + "Bread", "White Bread", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Wholemeal Bread", "Wholemeal Bread", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Banana Bread", "Banana Bread", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Raisin Bread", "Raisin Bread", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Corn Bread", "Corn Bread", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Sourdough Bread", "Sourdough Bread", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #3: White Bread

	void passage3_Init()
	{
		this.Passages[@"White Bread"] = new StoryPassage(@"White Bread", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("White bread is a classic and that is all there is not say. Nothing exciting but a" +
		    " safe bet.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Cut your loaf of bread into slices", "Cut your loaf of bread into slices", null);
		yield return text(".");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #4: Wholemeal Bread

	void passage4_Init()
	{
		this.Passages[@"Wholemeal Bread"] = new StoryPassage(@"Wholemeal Bread", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("This is a good option. It is healthier than white bread which is great.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("You bake this bread effortlessly.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("The bread is looking delicious and you continue with the process of preparing it." +
		    "");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("After some time your loaf of bread is done.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Cut your loaf of bread into slices", "Cut your loaf of bread into slices", null);
		yield return text(".");
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #5: Banana Bread

	void passage5_Init()
	{
		this.Passages[@"Banana Bread"] = new StoryPassage(@"Banana Bread", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("Sweet bread in not good for a sandwich lets accept that.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("choose another bread.", "First start by choosing which bread to make:", null);
		yield break;
	}


	// .............
	// #6: Raisin Bread

	void passage6_Init()
	{
		this.Passages[@"Raisin Bread"] = new StoryPassage(@"Raisin Bread", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Nobody likes raisins but if you are one of those weirdos who do you may ");
		yield return link("continue cooking", "continue cooking", null);
		yield return text(".");
		yield break;
	}


	// .............
	// #7: Corn Bread

	void passage7_Init()
	{
		this.Passages[@"Corn Bread"] = new StoryPassage(@"Corn Bread", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("Corn bread can only be made in thanksgiving you dummy dummy.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("And it may taste weird in a sandwich form?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Choose another bread.", "First start by choosing which bread to make:", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #8: Sourdough Bread

	void passage8_Init()
	{
		this.Passages[@"Sourdough Bread"] = new StoryPassage(@"Sourdough Bread", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return lineBreak();
		yield return text("Sourdough bread is only sold in the United States, if you live in the U.S. you ma" +
		    "y ");
		yield return link("use this bread", "use this bread", null);
		yield return text(" for your sandwich.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("I don" + "\'" + "t live in the U.S.", "First start by choosing which bread to make:", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #9: use this bread

	void passage9_Init()
	{
		this.Passages[@"use this bread"] = new StoryPassage(@"use this bread", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		using (styleScope("strong", true)) {
			yield return text("This is the recepie to make this type of bread, but there is some things wrong. F" +
		    "ind the issues with the recepie.");
		}
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Ingredients");
		yield return lineBreak();
		yield return text("1 1/2 teaspoons instant yeast");
		yield return lineBreak();
		yield return text("1 1/2 teaspoons salt");
		yield return lineBreak();
		yield return text("1 1/2 teaspoons sugar");
		yield return lineBreak();
		yield return text("2 1/2 cups (298g) Flour");
		yield return lineBreak();
		yield return text("2 cups (454g) ripe (fed) sourdough starter");
		yield return lineBreak();
		yield return text("1/2 cup (113g) lukewarm water");
		yield return lineBreak();
		yield return lineBreak();
		yield return htmlTag("hr");
		yield return text("1. Combine all the ingredients and mix and knead — by hand, mixer, or bread machi" +
		    "ne — to make a soft, smooth dough; about 15 to 20 minutes by hand, 7 to 10 minut" +
		    "es in a mixer, and 20 to 30 minutes in a bread machine.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("2. Place the dough in a lightly greased bowl and let it rise for 45 to 60 minutes" +
		    ", until puffy but not necessarily doubled in bulk.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("3. Lightly grease a 9\" x 5\" loaf pan.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("4. On a lightly greased work surface, gently deflate the dough, and form it into " +
		    "a 9\" log. Place the log in the prepared pan, cover, and let it rise for 60 to 90" +
		    " minutes, until it crests about 1\" over the rim of the pan.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("5. Preheat the oven to ");
		yield return link(350 + "°F", "350°F", null);
		yield return text(" or ");
		yield return link(350 + "°C", "350°C", null);
		yield return text(".");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("6. Bake the bread for 40 to 50 minutes, until it\'s light gold and a digital therm" +
		    "ometer inserted into the center reads 190°F.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("7. Remove the bread from the oven, and after a couple of minutes turn it out of t" +
		    "he pan onto a rack to cool. Store, well-wrapped, at room temperature for several" +
		    " days; freeze for longer storage.");
		yield break;
	}


	// .............
	// #10: The Bread Game

	void passage10_Init()
	{
		this.Passages[@"The Bread Game"] = new StoryPassage(@"The Bread Game", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		using (styleScope("strong", true)) {
			yield return text("The Bread Game");
		}
		yield return lineBreak();
		yield return lineBreak();
		yield return htmlTag("hr");
		yield return lineBreak();
		yield return link("Start Game", "Bread", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("I don" + "\'" + "t want to play", "I don\'t want to play", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #11: I don't want to play

	void passage11_Init()
	{
		this.Passages[@"I don't want to play"] = new StoryPassage(@"I don't want to play", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("Then why are you here?");
		yield break;
	}


	// .............
	// #12: 350°F

	void passage12_Init()
	{
		this.Passages[@"350°F"] = new StoryPassage(@"350°F", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("You come back to check on your bread after the alarm you set sounds.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("The bread is looking delicious and you continue with the process of preparing it." +
		    "");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("After some time your loaf of bread is done.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Cut your loaf of bread into slices", "Cut your loaf of bread into slices", null);
		yield return text(".");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #13: 350°C

	void passage13_Init()
	{
		this.Passages[@"350°C"] = new StoryPassage(@"350°C", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("You preheat your oven, then you add your dough and let your loaf cook.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("After 40 minutes you come back to check on your bread.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("You see that the dough is completly black. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("What do you do? You ");
		yield return link("take the bread out", "take the bread out", null);
		yield return text(" or you ");
		yield return link("leave it in there", "leave it in there", null);
		yield return text("?");
		yield break;
	}


	// .............
	// #14: take the bread out

	void passage14_Init()
	{
		this.Passages[@"take the bread out"] = new StoryPassage(@"take the bread out", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text(@"You take the tray out but you forgot to grab the mittens to protect your hands. You drop the tray. The tray falls against the curtains and they are set on fire. You do not own a fire extinguisher so you freak out. The neighbours sees the smoke and call the firefighters. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Your house is in ashes. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Restart the game.", "The Bread Game", null);
		yield break;
	}


	// .............
	// #15: leave it in there

	void passage15_Init()
	{
		this.Passages[@"leave it in there"] = new StoryPassage(@"leave it in there", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("Since you decided to leave the bread in the oven, it caught fire and therefore yo" +
		    "ur oven caught fire. You do not own a fire extinguisher so you freak out. The ne" +
		    "ighbours sees the smoke and call the firefighters. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Your house is in ashes. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Restart the game.", "The Bread Game", null);
		yield break;
	}


	// .............
	// #16: continue cooking

	void passage16_Init()
	{
		this.Passages[@"continue cooking"] = new StoryPassage(@"continue cooking", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		using (styleScope("strong", true)) {
			yield return text("This is the recepie to make this type of bread, but there is some things wrong. F" +
		    "ind the issues with the recepie.");
		}
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Ingredients");
		yield return lineBreak();
		yield return text("1 (1/4-ounce) package active dry yeast (2 1/4 teaspoons)");
		yield return lineBreak();
		yield return text("1/4 cup water (warm, about 110 F)");
		yield return lineBreak();
		yield return text("1 cup raisins");
		yield return lineBreak();
		yield return text("1/4 cup butter (softened)");
		yield return lineBreak();
		yield return text("1/4 cup granulated sugar");
		yield return lineBreak();
		yield return text("1 1/2 teaspoons salt");
		yield return lineBreak();
		yield return text("1/2 cup milk (warm)");
		yield return lineBreak();
		yield return text("3 3/4 cups all-purpose flour (divided)");
		yield return lineBreak();
		yield return text("2 large eggs (beaten)");
		yield return lineBreak();
		yield return lineBreak();
		yield return htmlTag("hr");
		yield return text("1. Gather the ingredients.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("2. Dissolve the yeast in the warm water.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("3. In a large bowl, combine the raisins, butter, sugar, salt, and warm milk; stir" +
		    " to dissolve the sugar. Let the mixture cool to lukewarm.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("4. Stir 1 1/2 cups of the flour into the milk mixture and beat until smooth.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("5. Add the yeast mixture and the beaten eggs to the milk mixture and mix to blend" +
		    " well.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("6. Add enough of the remaining flour to make a soft but stiff dough.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("7. Turn the dough out onto a lightly floured surface and knead for about 10 minut" +
		    "es, or until the dough is smooth and elastic.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("8. Butter or oil a large bowl. Place the dough in the greased bowl. Turn it over " +
		    "to grease the entire surface of the dough.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("9. Cover the bowl with a clean kitchen towel and let it stand in a warm, draft-fr" +
		    "ee place until it has doubled in bulk, about 1 to 1 1/2 hours.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("10. Punch the dough down and divide it into two equal portions. Cover the dough w" +
		    "ith a kitchen towel and let it rest for 10 minutes.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("11. Shape the dough into two loaves and place them in two greased 8-by-4-inch loa" +
		    "f pans.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("12. Cover the pans with a kitchen towel and let the loaves rise for about 45 to 6" +
		    "0 minutes, or until the dough has almost doubled in bulk.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("13. Bake at ");
		yield return link(350 + "°C", "350°C", null);
		yield return text(" or ");
		yield return link(350 + "°F", "350°F", null);
		yield return text("  for 25 minutes. Place foil over the loaves for the last 10 minutes if they look" +
		    " overly brown.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("14. Remove the loaves from the pans and let them cool on racks.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("15. Serve and enjoy!");
		yield break;
	}


	// .............
	// #17: Cut your loaf of bread into slices

	void passage17_Init()
	{
		this.Passages[@"Cut your loaf of bread into slices"] = new StoryPassage(@"Cut your loaf of bread into slices", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("You have a whole set of knifs. Choose the best one to cut your bread.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Hunting Knife", "Hunting Knife", null);
		yield return lineBreak();
		yield return htmlTag("</style>");
		yield return lineBreak();
		yield return htmlTag("<img src=https://www.buckknives.com/images/products/hero/0120BRS-B.jpg>");
		yield return lineBreak();
		yield return htmlTag("</div>");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Kitchen Knife", "Kitchen Knife", null);
		yield return lineBreak();
		yield return htmlTag("</style>");
		yield return lineBreak();
		yield return htmlTag("<img src=https://www.rmurphyknives.com/store/media/Cooking/ChefsSelect/Chef8/CH8CIIHO2500x1667.jpg>");
		yield return lineBreak();
		yield return htmlTag("</div>");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Butcher Knife", "Butcher Knife", null);
		yield return lineBreak();
		yield return htmlTag("</style>");
		yield return lineBreak();
		yield return htmlTag("<img src=https://images-na.ssl-images-amazon.com/images/I/514bJbnaEHL._SX466_.jpg>");
		yield return lineBreak();
		yield return htmlTag("</div>");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Butter Knife", "Butter Knife", null);
		yield return lineBreak();
		yield return htmlTag("</style>");
		yield return lineBreak();
		yield return htmlTag("<img src=https://www.sohohome.com/us/media/catalog/product/cache/12/image/2000x/bcf7ce64d63d93f1f374273bba74938d/h/o/house_butter_knife_1.jpg>");
		yield return lineBreak();
		yield return htmlTag("</div>");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Serrated Knife", "Serrated Knife", null);
		yield return lineBreak();
		yield return htmlTag("</style>");
		yield return lineBreak();
		yield return htmlTag("<img src=https://images-na.ssl-images-amazon.com/images/I/61ECcAR89xL._SL1500_.jpg>");
		yield return lineBreak();
		yield return htmlTag("</div>");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #18: Kitchen Knife

	void passage18_Init()
	{
		this.Passages[@"Kitchen Knife"] = new StoryPassage(@"Kitchen Knife", new string[]{  }, passage18_Main);
	}

	IStoryThread passage18_Main()
	{
		yield return text("This knife is made for cutting a lot of things effectivly without damaging it the" +
		    "refore it is not serrated. This means that it is ");
		using (styleScope("em", true)) {
			yield return text("not easy");
		}
		yield return text(" to cut the bread and it takes a lot of time.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Eventualy you cut the bread but ruin your knife. Which makes you kind of happy bu" +
		    "t now you have to buy a new knife.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Continue on your sandwichmaking path", "Continue on your sandwichmaking path", null);
		yield break;
	}


	// .............
	// #19: Butcher Knife

	void passage19_Init()
	{
		this.Passages[@"Butcher Knife"] = new StoryPassage(@"Butcher Knife", new string[]{  }, passage19_Main);
	}

	IStoryThread passage19_Main()
	{
		yield return text("You grab the big butcher knife and lift it. Swinging the knife with force and vel" +
		    "ocity you close your eyes and feel how it cuts through something.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("You feel a rush of pain going to your body. As you open your eyes you see the who" +
		    "le table painted in red and your hand separated from your body.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Screaming in pain you fall over and knock the bread to the ground. You ");
		using (styleScope("em", true)) {
			yield return text("die");
		}
		yield return text(" from the shock of loosing your hand and making the bread dirty.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Restart the game.", "The Bread Game", null);
		yield break;
	}


	// .............
	// #20: Butter Knife

	void passage20_Init()
	{
		this.Passages[@"Butter Knife"] = new StoryPassage(@"Butter Knife", new string[]{  }, passage20_Main);
	}

	IStoryThread passage20_Main()
	{
		yield return text("You try and cut the bread but it seems to be very diffucult. Nontheless you try t" +
		    "o cut the bread. This creates enough friction to burn the bread and melt the kni" +
		    "fe.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("You know find your loaf of bread to be ");
		using (styleScope("em", true)) {
			yield return text("burnt and coated in silver");
		}
		yield return text(".");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("You can no longer eat your bread.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Restart the game.", "The Bread Game", null);
		yield break;
	}


	// .............
	// #21: Serrated Knife

	void passage21_Init()
	{
		this.Passages[@"Serrated Knife"] = new StoryPassage(@"Serrated Knife", new string[]{  }, passage21_Main);
	}

	IStoryThread passage21_Main()
	{
		yield return text("This is the perfect knife for cutting bread, especially if its a hard bread. You " +
		    "made the ");
		using (styleScope("em", true)) {
			yield return text("perfect");
		}
		yield return text(" choice.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Continue on your sandwichmaking path", "Continue on your sandwichmaking path", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #22: Hunting Knife

	void passage22_Init()
	{
		this.Passages[@"Hunting Knife"] = new StoryPassage(@"Hunting Knife", new string[]{  }, passage22_Main);
	}

	IStoryThread passage22_Main()
	{
		yield return text("This hunting knife cuts extremly well as if everything and anything was butter th" +
		    "erefore you cut the bread effortlesly.");
		yield return lineBreak();
		yield return text("You are cutting all the slices carelessly and because of this you do not notice a" +
		    "s you ");
		using (styleScope("em", true)) {
			yield return text("slash");
		}
		yield return text(" your four fingers. Blood is spraying everywere. It ruins the bread, the countert" +
		    "ops, the walls and the floor. You faint and loose all your blood.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("You should be carefull when you use sharp knifes.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Restart the game.", "The Bread Game", null);
		yield break;
	}


	// .............
	// #23: Continue on your sandwichmaking path

	void passage23_Init()
	{
		this.Passages[@"Continue on your sandwichmaking path"] = new StoryPassage(@"Continue on your sandwichmaking path", new string[]{  }, passage23_Main);
	}

	IStoryThread passage23_Main()
	{
		yield return text("Now, you need to add all the other ingredients to make the perfect sandwich.");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Continue on your sandwich making journey", "Continue on your sandwich making journey", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #24: Continue on your sandwich making journey

	void passage24_Init()
	{
		this.Passages[@"Continue on your sandwich making journey"] = new StoryPassage(@"Continue on your sandwich making journey", new string[]{  }, passage24_Main);
	}

	IStoryThread passage24_Main()
	{
		yield return text("You have made a beautiful loaf of bread and cut it into slices now you just need " +
		    "to finish it.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("As you add all of the other ingredients you realize that you are alergic to wheat" +
		    " and yeast so you ");
		using (styleScope("em", true)) {
			yield return text("cannot");
		}
		yield return text(" actually eat bread or anything similar so now you have wasted a huge amount of p" +
		    "roducts and time ");
		using (styleScope("em", true)) {
			yield return text("oops");
		}
		yield return text(".");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Now you only have three options.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Put the food in the ");
		yield return link("organic", "organic", null);
		yield return text(" trash bin or the ");
		yield return link("inorganic", "inorganic", null);
		yield return text(".");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Or you can ");
		yield return link("ignore the fact that you are allergic to wheat and yeast", "ignore the fact that you are allergic to wheat and yeast", null);
		yield return text(".");
		yield break;
	}


	// .............
	// #25: organic

	void passage25_Init()
	{
		this.Passages[@"organic"] = new StoryPassage(@"organic", new string[]{  }, passage25_Main);
	}

	IStoryThread passage25_Main()
	{
		yield return text("Great!!! At least you are consious about the planet and did not die.");
		yield return lineBreak();
		yield return lineBreak();
		using (styleScope("em", true)) {
			yield return text("Congratulations");
		}
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Restart the game.", "The Bread Game", null);
		yield break;
	}


	// .............
	// #26: inorganic

	void passage26_Init()
	{
		this.Passages[@"inorganic"] = new StoryPassage(@"inorganic", new string[]{  }, passage26_Main);
	}

	IStoryThread passage26_Main()
	{
		yield return text("Food is organic, you should put your sandwich with all the other organic things s" +
		    "o its better for the earth.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("TAKE CARE OF YOUR PLANET");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Change to ");
		yield return link("organic", "organic", null);
		yield return text(".");
		yield break;
	}


	// .............
	// #27: ignore the fact that you are allergic to wheat and yeast

	void passage27_Init()
	{
		this.Passages[@"ignore the fact that you are allergic to wheat and yeast"] = new StoryPassage(@"ignore the fact that you are allergic to wheat and yeast", new string[]{  }, passage27_Main);
	}

	IStoryThread passage27_Main()
	{
		yield return lineBreak();
		yield return text("Are you sure you want to ");
		yield return link("ignore the fact that you are allergic to wheat and yeast???", "ignore the fact that you are allergic to wheat and yeast???", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Sorry, take me ");
		yield return link("back", "Continue on your sandwich making journey", null);
		yield break;
	}


	// .............
	// #28: ignore the fact that you are allergic to wheat and yeast???

	void passage28_Init()
	{
		this.Passages[@"ignore the fact that you are allergic to wheat and yeast???"] = new StoryPassage(@"ignore the fact that you are allergic to wheat and yeast???", new string[]{  }, passage28_Main);
	}

	IStoryThread passage28_Main()
	{
		yield return text("Since you ignored the fact that you are allergic to wheat and yeast you spent you" +
		    "r last day enjoying an awsome, flavourfull and rich in wheat and yeast sandwich," +
		    " deemed the best sandwich of your county.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Sadly you could not enjoy the fame that came with the creation of the best sandwi" +
		    "ch in your county since you died because of your allergic reaction.");
		yield return lineBreak();
		yield return lineBreak();
		using (styleScope("em", true)) {
			yield return text("Congratulations you kind of won");
		}
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Restart the game.", "The Bread Game", null);
		yield break;
	}


}